apiVersion: v1 
kind: Pod
metadata:
  name: cm-demo
spec:
  containers:
    - name: demo-container
      image: busybox
      command: ["/bin/sh", "-c", "env && sleep 3600"]
      env:
        - name: APP_COLOUR
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_COLOUR
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_MODE
      volumeMounts:
        - mountPath: /etc/config
          name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: my-config
